import type { Metadata } from "next";
import { Box, Container, CssBaseline, ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { theme } from "./_theme";
import "./style.css";
import AppHeader from "./_components/AppHeader";
import DataContextProvider from "./data";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body className="app-body">
                <AppRouterCacheProvider>
                    <CssBaseline />
                    <ThemeProvider theme={theme}>
                        <DataContextProvider>
                            <Container
                                sx={{
                                    maxWidth: "1000px",
                                    paddingTop: "50px"
                                }}
                            >
                                <AppHeader />
                                <Box sx={{paddingTop: "50px"}}>{children}</Box>
                            </Container>
                        </DataContextProvider>
                    </ThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
